#!/usr/bin/env python3
"""Compile project/tokens.json into dist/tokens.css.

The design system artifact generates its own tokens.css for its previews.
This does the same job for the repo, so a consuming app has a static file to
vendor without talking to anything. Run it after editing tokens.json.
"""
from __future__ import annotations

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
TOKENS = json.loads((ROOT / "project" / "tokens.json").read_text(encoding="utf-8"))


def theme_value(token: dict, theme: str, first: str) -> str | None:
    value = token["value"]
    if isinstance(value, str):
        return value if theme == first else None
    return value.get(theme)


def render(value: str) -> str:
    # An alias "{other}" compiles to a reference to that token.
    if value.startswith("{") and value.endswith("}"):
        return f"var(--{value[1:-1]})"
    return value


def main() -> None:
    themes = [t["id"] for t in TOKENS["color"]["themes"]]
    first = themes[0]
    out: list[str] = ["/* Generated by tools/build-tokens.py. Do not edit. */", ""]

    out.append(f':root, [data-theme="{first}"] {{')
    for token in TOKENS["color"]["tokens"]:
        value = theme_value(token, first, first)
        if value:
            out.append(f'  --{token["name"]}: {render(value)};')
    out.append("}")
    out.append("")

    for theme in themes[1:]:
        out.append(f'[data-theme="{theme}"] {{')
        for token in TOKENS["color"]["tokens"]:
            value = theme_value(token, theme, first)
            if value:
                out.append(f'  --{token["name"]}: {render(value)};')
        out.append("}")
        out.append("")

    out.append(":root {")
    for family in ("spacing", "radius"):
        for token in TOKENS.get(family, {}).get("tokens", []):
            out.append(f'  --{token["name"]}: {token["value"]};')
    for key, stack in TOKENS["type"]["families"].items():
        out.append(f"  --font-{key}: {stack};")
    out.append("}")
    out.append("")

    for group in TOKENS["type"]["groups"]:
        family = group.get("family", "sans")
        for style in group["styles"]:
            decls = [
                f'font-family: var(--font-{style.get("family", family)})',
                f'font-size: {style["fontSize"]}',
                f'line-height: {style["lineHeight"]}',
                f'font-weight: {style["fontWeight"]}',
            ]
            if "letterSpacing" in style:
                decls.append(f'letter-spacing: {style["letterSpacing"]}')
            body = "; ".join(decls)
            out.append(f'.{style["name"]} {{ {body}; }}')

    (ROOT / "dist").mkdir(exist_ok=True)
    (ROOT / "dist" / "tokens.css").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote dist/tokens.css ({len(TOKENS['color']['tokens'])} colors, {len(themes)} themes)")


if __name__ == "__main__":
    main()
